name: Flutter Build APK

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Create .env file
        run: |
          echo "API_URL=${{ secrets.API_URL }}" > .env
          echo "BETTER_AUTH_URL=${{ secrets.BETTER_AUTH_URL }}" >> .env

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Split per ABI)
        run: flutter build apk --release --split-per-abi

      - name: Ubah Nama File APK biar Jelas
        run: |
          mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/app/outputs/flutter-apk/dlh-presensi-HP-Baru-arm64.apk
          mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk build/app/outputs/flutter-apk/dlh-presensi-HP-Lama-arm32.apk
          mv build/app/outputs/flutter-apk/app-x86_64-release.apk build/app/outputs/flutter-apk/dlh-presensi-Emulator-x86.apk

      - name: Publish ke Halaman Utama GitHub (Release)
        uses: ncipollo/release-action@v1
        if: github.event_name != 'pull_request'
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
          name: "Aplikasi Presensi DLH (Versi Terbaru)"
          body: "Silakan unduh file `.apk` yang sesuai dengan perangkat Android Anda di bagian **Assets** di bawah ini.\n- Gunakan `HP-Baru` untuk Android modern.\n- Gunakan `HP-Lama` untuk Android versi lama."
          artifacts: "build/app/outputs/flutter-apk/*.apk"
