name: Flutter Build APK

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Hanya ARM64)
        env:
          APP_ID_SUFFIX: .github
          API_URL: ${{ secrets.API_URL }}
          BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
        run: |
          API_URL_CLEAN=$(echo "$API_URL" | tr -d '\n' | tr -d '\r')
          BETTER_AUTH_URL_CLEAN=$(echo "$BETTER_AUTH_URL" | tr -d '\n' | tr -d '\r')
          flutter build apk --release --target-platform android-arm64 --build-name="0.0.1-beta.${{ github.run_number }}" --build-number="${{ github.run_number }}" --dart-define="API_URL=$API_URL_CLEAN" --dart-define="BETTER_AUTH_URL=$BETTER_AUTH_URL_CLEAN"

      - name: Ubah Nama File APK
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/dlh-presensi-v0.0.1-beta.${{ github.run_number }}-arm64.apk

      - name: Publish ke Halaman Utama GitHub (Release)
        uses: ncipollo/release-action@v1
        if: github.event_name != 'pull_request'
        with:
          tag: "v0.0.1-beta.${{ github.run_number }}"
          name: "v0.0.1-beta.${{ github.run_number }}"
          prerelease: true
          allowUpdates: true
          body: "Silakan unduh file `.apk` versi beta untuk perangkat Android (ARM64)."
          artifacts: "build/app/outputs/flutter-apk/*.apk"
